export interface Product {
  id: string;
  placeId: string;
  name: string;
  type: 'cake' | 'sandwich' | 'pastry';
  originalPrice: number;
  discountedPrice: number;
  discountPercentage: number;
  quantityLeft: number;
  image: string;
  description: string;
  expiringInHours: number; // <1 for red, else green
  freshnessGuarantee: boolean;
}

export interface Place {
  id: string;
  name: string;
  address: string;
  location: {
    latitude: number;
    longitude: number;
  };
  products: Product[];
}

export const places: Place[] = [
  {
    id: 'p1',
    name: 'Bono Bakery',
    address: '4 Chinggis Ave',
    location: { latitude: 47.9138, longitude: 106.9139 },
    products: [
      {
        id: '1',
        placeId: 'p1',
        name: 'Chocolate Truffle Cake',
        type: 'cake',
        originalPrice: 45,
        discountedPrice: 30,
        discountPercentage: 33,
        quantityLeft: 5,
        image: 'https://images.unsplash.com/photo-1612874745482-367a73aa7f1c?auto=format&fit=crop&w=800&q=80',
        description: 'Rich chocolate cake with truffle filling',
        expiringInHours: 0.8,
        freshnessGuarantee: true,
      },
      {
        id: '2',
        placeId: 'p1',
        name: 'Matcha Roll',
        type: 'pastry',
        originalPrice: 7,
        discountedPrice: 5,
        discountPercentage: 29,
        quantityLeft: 8,
        image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
        description: 'Soft roll with cream and matcha powder',
        expiringInHours: 1.3,
        freshnessGuarantee: true,
      },
    ],
  },
  {
    id: 'p2',
    name: 'Mongolian Bakery',
    address: '13 Peace Ave',
    location: { latitude: 47.9081, longitude: 106.8851 },
    products: [
      {
        id: '3',
        placeId: 'p2',
        name: 'Blueberry Cheesecake',
        type: 'cake',
        originalPrice: 55,
        discountedPrice: 38,
        discountPercentage: 31,
        quantityLeft: 4,
        image: 'https://images.unsplash.com/photo-1568632068825-4e6001b71b89?auto=format&fit=crop&w=800&q=80',
        description: 'Creamy cheesecake with blueberry topping and crunchy crust',
        expiringInHours: 1.5,
        freshnessGuarantee: true,
      },
      {
        id: '4',
        placeId: 'p2',
        name: 'Almond Croissant',
        type: 'pastry',
        originalPrice: 9,
        discountedPrice: 7,
        discountPercentage: 22,
        quantityLeft: 6,
        image: 'https://images.unsplash.com/photo-1532535070422-8d12b0f0b04f?auto=format&fit=crop&w=800&q=80',
        description: 'Flaky pastry with almond filling',
        expiringInHours: 2.2,
        freshnessGuarantee: true,
      },
    ],
  },
  {
    id: 'p3',
    name: 'Golden Dough',
    address: '20 Peace Ave',
    location: { latitude: 47.9103, longitude: 106.9163 },
    products: [
      {
        id: '5',
        placeId: 'p3',
        name: 'Cinnamon Roll',
        type: 'pastry',
        originalPrice: 7,
        discountedPrice: 4,
        discountPercentage: 43,
        quantityLeft: 10,
        image: 'https://images.unsplash.com/photo-1617196031841-3649072fcbf6?auto=format&fit=crop&w=800&q=80',
        description: 'Warm cinnamon roll with sweet glaze',
        expiringInHours: 0.6,
        freshnessGuarantee: true,
      },
      {
        id: '6',
        placeId: 'p3',
        name: 'Ham Cheese Sandwich',
        type: 'sandwich',
        originalPrice: 12,
        discountedPrice: 9,
        discountPercentage: 25,
        quantityLeft: 7,
        image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=80',
        description: 'Toasted sandwich with ham, cheese, and salad',
        expiringInHours: 3.5,
        freshnessGuarantee: true,
      },
    ],
  },
  {
    id: 'p4',
    name: 'Cupcake Lounge',
    address: '7 Ulaanbaatar St',
    location: { latitude: 47.9145, longitude: 106.9247 },
    products: [
      {
        id: '7',
        placeId: 'p4',
        name: 'Red Velvet Cupcake',
        type: 'cake',
        originalPrice: 8,
        discountedPrice: 5,
        discountPercentage: 37,
        quantityLeft: 12,
        image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=800&q=80',
        description: 'Soft red velvet cupcake with cream cheese frosting',
        expiringInHours: 1.8,
        freshnessGuarantee: true,
      },
    ],
  },
  {
    id: 'p5',
    name: 'City Slice Bakery',
    address: '2 Narnii Zam',
    location: { latitude: 47.9213, longitude: 106.9182 },
    products: [
      {
        id: '8',
        placeId: 'p5',
        name: 'Cheese Danish',
        type: 'pastry',
        originalPrice: 6,
        discountedPrice: 4,
        discountPercentage: 33,
        quantityLeft: 15,
        image: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=800&q=80',
        description: 'Buttery pastry with sweet cheese filling',
        expiringInHours: 2.4,
        freshnessGuarantee: true,
      },
    ],
  },
  {
    id: 'p6',
    name: 'Sweet Morning',
    address: '11 Sukhbaatar Square',
    location: { latitude: 47.9212, longitude: 106.9056 },
    products: [
      {
        id: '9',
        placeId: 'p6',
        name: 'Coconut Tart',
        type: 'pastry',
        originalPrice: 9,
        discountedPrice: 6,
        discountPercentage: 33,
        quantityLeft: 9,
        image: 'https://images.unsplash.com/photo-1618330848625-aa4e8647c0b8?auto=format&fit=crop&w=800&q=80',
        description: 'Crisp tart with creamy coconut almond filling',
        expiringInHours: 2.1,
        freshnessGuarantee: true,
      },
      {
        id: '10',
        placeId: 'p6',
        name: 'Smoked Salmon Bagel',
        type: 'sandwich',
        originalPrice: 14,
        discountedPrice: 11,
        discountPercentage: 21,
        quantityLeft: 8,
        image: 'https://images.unsplash.com/photo-1606755962771-2ee269011968?auto=format&fit=crop&w=800&q=80',
        description: 'Bagel with cream cheese, salmon, and arugula',
        expiringInHours: 3.8,
        freshnessGuarantee: true,
      },
    ],
  },
  {
    id: 'p7',
    name: 'Mezza Bakery',
    address: '25 Seoul St',
    location: { latitude: 47.9045, longitude: 106.9223 },
    products: [
      {
        id: '11',
        placeId: 'p7',
        name: 'Garlic Bread',
        type: 'sandwich',
        originalPrice: 7,
        discountedPrice: 5,
        discountPercentage: 29,
        quantityLeft: 18,
        image: 'https://images.unsplash.com/photo-1512058564366-c9e2e0a7b864?auto=format&fit=crop&w=800&q=80',
        description: 'Toasted bread topped with garlic butter and parmesan',
        expiringInHours: 4.0,
        freshnessGuarantee: true,
      },
    ],
  },
  {
    id: 'p8',
    name: 'Deli Corner',
    address: '33 Zaisan Road',
    location: { latitude: 47.8903, longitude: 106.9440 },
    products: [
      {
        id: '12',
        placeId: 'p8',
        name: 'Banana Bread',
        type: 'cake',
        originalPrice: 10,
        discountedPrice: 7,
        discountPercentage: 30,
        quantityLeft: 12,
        image: 'https://images.unsplash.com/photo-1512058564366-c9e2e0a7b864?auto=format&fit=crop&w=800&q=80',
        description: 'Moist banana bread with walnuts',
        expiringInHours: 1.7,
        freshnessGuarantee: true,
      },
    ],
  },
  {
    id: 'p9',
    name: 'Highland Bakery',
    address: '55 Peace Ave',
    location: { latitude: 47.9244, longitude: 106.9231 },
    products: [
      {
        id: '13',
        placeId: 'p9',
        name: 'Black Forest Cake',
        type: 'cake',
        originalPrice: 50,
        discountedPrice: 34,
        discountPercentage: 32,
        quantityLeft: 4,
        image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
        description: 'Chocolate cake with cherries and whipped cream',
        expiringInHours: 1.2,
        freshnessGuarantee: true,
      },
    ],
  },
  {
    id: 'p10',
    name: 'Morning Crush',
    address: '10 Narlag Ave',
    location: { latitude: 47.9149, longitude: 106.9238 },
    products: [
      {
        id: '14',
        placeId: 'p10',
        name: 'Egg Salad Sandwich',
        type: 'sandwich',
        originalPrice: 9,
        discountedPrice: 7,
        discountPercentage: 22,
        quantityLeft: 10,
        image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=80',
        description: 'Classic egg salad on sourdough',
        expiringInHours: 3.2,
        freshnessGuarantee: true,
      },
    ],
  },
  {
    id: 'p11',
    name: 'Elegant Bakes',
    address: '18 Sukhbaatar St',
    location: { latitude: 47.9208, longitude: 106.9127 },
    products: [
      {
        id: '15',
        placeId: 'p11',
        name: 'Pecan Pie',
        type: 'cake',
        originalPrice: 42,
        discountedPrice: 29,
        discountPercentage: 31,
        quantityLeft: 6,
        image: 'https://images.unsplash.com/photo-1542831371-d531d36971e6?auto=format&fit=crop&w=800&q=80',
        description: 'Sweet pecan pie with flaky crust',
        expiringInHours: 2.0,
        freshnessGuarantee: true,
      },
    ],
  },
  {
    id: 'p12',
    name: 'Dough Delight',
    address: '31 Narcissus Mach',
    location: { latitude: 47.9157, longitude: 106.9277 },
    products: [
      {
        id: '16',
        placeId: 'p12',
        name: 'Red Bean Puff',
        type: 'pastry',
        originalPrice: 6,
        discountedPrice: 4,
        discountPercentage: 33,
        quantityLeft: 15,
        image: 'https://images.unsplash.com/photo-1533801915804-2dd05be3c8f5?auto=format&fit=crop&w=800&q=80',
        description: 'Crispy puff with sweet red bean paste',
        expiringInHours: 1.3,
        freshnessGuarantee: true,
      },
    ],
  },
  {
    id: 'p13',
    name: 'Bakery Boulevard',
    address: '42 Peace Ave',
    location: { latitude: 47.9227, longitude: 106.9132 },
    products: [
      {
        id: '17',
        placeId: 'p13',
        name: 'Garlic Cream Roll',
        type: 'pastry',
        originalPrice: 7,
        discountedPrice: 5,
        discountPercentage: 29,
        quantityLeft: 13,
        image: 'https://images.unsplash.com/photo-1481833761820-0509d3217039?auto=format&fit=crop&w=800&q=80',
        description: 'Savory roll with garlic cream center',
        expiringInHours: 2.4,
        freshnessGuarantee: true,
      },
    ],
  },
  {
    id: 'p14',
    name: 'City Oven',
    address: '16 Gorkhi',
    location: { latitude: 47.9152, longitude: 106.9087 },
    products: [
      {
        id: '18',
        placeId: 'p14',
        name: 'Multi-grain Baguette',
        type: 'sandwich',
        originalPrice: 8,
        discountedPrice: 6,
        discountPercentage: 25,
        quantityLeft: 14,
        image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
        description: 'Crunchy baguette with seeds and herbs',
        expiringInHours: 3.4,
        freshnessGuarantee: true,
      },
    ],
  },
  {
    id: 'p15',
    name: 'Rose Corner',
    address: '19 Dashbalbar',
    location: { latitude: 47.9165, longitude: 106.9183 },
    products: [
      {
        id: '19',
        placeId: 'p15',
        name: 'Carrot Cake',
        type: 'cake',
        originalPrice: 48,
        discountedPrice: 33,
        discountPercentage: 31,
        quantityLeft: 5,
        image: 'https://images.unsplash.com/photo-1516685018646-549d46f58c5d?auto=format&fit=crop&w=800&q=80',
        description: 'Moist carrot cake with cream cheese icing',
        expiringInHours: 1.6,
        freshnessGuarantee: true,
      },
    ],
  },
  {
    id: 'p16',
    name: 'Nordic Bakes',
    address: '22 Nordic Ave',
    location: { latitude: 47.9140, longitude: 106.9280 },
    products: [
      {
        id: '20',
        placeId: 'p16',
        name: 'Lemon Meringue Pie',
        type: 'cake',
        originalPrice: 52,
        discountedPrice: 37,
        discountPercentage: 29,
        quantityLeft: 5,
        image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
        description: 'Tart lemon filling topped with toasted meringue',
        expiringInHours: 1.1,
        freshnessGuarantee: true,
      },
    ],
  },
];

export const mockProducts: Product[] = places.flatMap((place) =>
  place.products.map((product) => ({
    ...product,
    placeId: place.id,
  })),
);
